# Desired state for "orders-api" in PROD. Missing instance -> promoted from PRE-PROD.
apiInstance:
  assetId: orders-api
  groupId: null
  assetVersion: "1.0.3"
  productVersion: v1
  instanceLabel: orders-api-prod
  deploymentType: cloudhub2
  endpoint:
    implementationUri: https://orders-backend.prod.svc.example.com:8443/
    type: http
    scheme: https
    port: 8081
    path: /
    withProxy: true
    muleVersion4OrAbove: true

promotion:
  fromEnvironment: preprod
  sourceInstanceLabel: orders-api-preprod
  copyPolicies: false
  copyTiers: true
  copyAlerts: true

prune: true

policies:
  - assetId: rate-limiting-sla
    groupId: 68ef9520-24e9-4cf2-b2f5-620025690913
    version: "1.4.0"
    order: 1
    configurationData:
      clusterizable: true
      exposeHeaders: true
      rateLimits:
        - maximumRequests: 1000
          timePeriodInMilliseconds: 60000

  - assetId: client-id-enforcement
    groupId: 68ef9520-24e9-4cf2-b2f5-620025690913
    version: "1.3.2"
    order: 2
    configurationData:
      credentialsOrigin: customExpression
      clientIdExpression: "#[attributes.headers['client_id']]"
      clientSecretExpression: "#[attributes.headers['client_secret']]"

  - assetId: json-threat-protection
    groupId: 68ef9520-24e9-4cf2-b2f5-620025690913
    version: "1.2.0"
    order: 3
    configurationData:
      maxContainerDepth: 20
      maxStringValueLength: 4000
      maxObjectEntryCount: 200
      maxArrayElementCount: 200
